apiVersion: v1
kind: Service
metadata:
  name: vault-internal
spec:
  clusterIP: None
  ports:
    - name: vault-api
      port: 8200
      targetPort: vault-api
    - name: vault-cluster
      port: 8201
      targetPort: vault-cluster
  selector:
    app: vault
